# Generated by Django 2.2.5 on 2019-12-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=64, unique=True)),
                ('a_desc', models.CharField(max_length=1024)),
                ('a_create_time', models.DateTimeField(auto_now_add=True)),
                ('a_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
            options={
                'db_table': 'blog_article',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_content', models.CharField(max_length=255, unique=True)),
                ('c_create_time', models.DateTimeField(auto_now_add=True)),
                ('c_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Article')),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
            options={
                'db_table': 'blog_comment',
            },
        ),
    ]
